// var div = document.getElementById('playground')
// var p =document.getElementsByClassName('text')
// var h1= document.getElementsByTagName('h1')
// console.log(div)
// console.log(p)
// console.log(h1)

var div = document.querySelector('#playground')
var p = document.querySelectorAll('.text')
var h1= document.querySelector('h1')
var ul = document.querySelectorAll('div#playground >ul li')
var ul1 = document.querySelectorAll('div#playground > div ul li')
console.log(div)
console.log(p)
console.log(h1)
console.log(ul)
console.log(ul1)
